class ModelUndangan {
  String? namaInstansi,
      jenisInstansi,
      noTlp,
      website,
      email,
      alamat,
      noSurat,
      lampiran,
      perihal,
      namaAcara,
      tempat,
      tglAcara,
      waktu,
      penerima,
      ketua,
      sekretaris,
      tempatTerbit,
      tglTerbit;
  ModelUndangan(
      {required this.namaInstansi,
      required this.jenisInstansi,
      required this.noTlp,
      this.website,
      required this.email,
      required this.alamat,
      required this.noSurat,
      required this.lampiran,
      required this.perihal,
      required this.namaAcara,
      required this.tempat,
      required this.tglAcara,
      required this.waktu,
      required this.penerima,
      required this.ketua,
      required this.sekretaris,
      required this.tempatTerbit,
      required this.tglTerbit});
}
