class ModelIzinKegiatan {
  String? namaInstansi,
      jenisInstansi,
      noTlp,
      website,
      alamat,
      noSurat,
      lampiran,
      perihal,
      namaAcara,
      tempat,
      tglAcara,
      waktu,
      penerima,
      ketua,
      tempatTerbit,
      tglTerbit;
  ModelIzinKegiatan(
      {required this.namaInstansi,
      required this.jenisInstansi,
      required this.noTlp,
      required this.website,
      required this.alamat,
      required this.noSurat,
      required this.lampiran,
      required this.perihal,
      required this.namaAcara,
      required this.tempat,
      required this.tglAcara,
      required this.waktu,
      required this.penerima,
      required this.ketua,
      required this.tempatTerbit,
      required this.tglTerbit});
}
